package DataAccess.Entities;

public class PerfilAdministrador {
    private int PERFIL_ADMINISTRADOR_ID;
    private String CONTRASENA_ADMINISTRADOR_NOMBRE;
    private String CEDULA_ADMINISTRADOR_NOMBRE;
    private String USUARIO_ADMINISTRADOR_NOMBRE;
    private String PERFIL_ADMINISTRADOR_ESTADO;
    private String NOMBRE_NUEVO;


    //Constructor de la tabla con sus respectivos parámetros para getters y setters
    public PerfilAdministrador (int PERFIL_ADMINISTRADOR_ID, String CONTRASENA_ADMINISTRADOR_NOMBRE, String CEDULA_ADMINISTRADOR_NOMBRE, String USUARIO_ADMINISTRADOR_NOMBRE, String PERFIL_ADMINISTRADOR_ESTADO){
        this.PERFIL_ADMINISTRADOR_ID = PERFIL_ADMINISTRADOR_ID;
        this.CONTRASENA_ADMINISTRADOR_NOMBRE = CONTRASENA_ADMINISTRADOR_NOMBRE;
        this.CEDULA_ADMINISTRADOR_NOMBRE  = CEDULA_ADMINISTRADOR_NOMBRE;
        this.USUARIO_ADMINISTRADOR_NOMBRE = USUARIO_ADMINISTRADOR_NOMBRE;
        this.PERFIL_ADMINISTRADOR_ESTADO = PERFIL_ADMINISTRADOR_ESTADO;
    }
    public PerfilAdministrador (int PERFIL_ADMINISTRADOR_ID, String USUARIO_ADMINISTRADOR_NOMBRE){
        this.PERFIL_ADMINISTRADOR_ID = PERFIL_ADMINISTRADOR_ID;
        this.USUARIO_ADMINISTRADOR_NOMBRE=USUARIO_ADMINISTRADOR_NOMBRE;
    }
    public PerfilAdministrador (String CEDULA_ADMINISTRADOR_NOMBRE, String CONTRASENA_ADMINISTRADOR_NOMBRE, String USUARIO_ADMINISTRADOR_NOMBRE){
        this.CEDULA_ADMINISTRADOR_NOMBRE = CEDULA_ADMINISTRADOR_NOMBRE;
        this.CONTRASENA_ADMINISTRADOR_NOMBRE = CONTRASENA_ADMINISTRADOR_NOMBRE;
        this.USUARIO_ADMINISTRADOR_NOMBRE = USUARIO_ADMINISTRADOR_NOMBRE;
    }
    public PerfilAdministrador (String USUARIO_ADMINISTRADOR_NOMBRE, String NOMBRE_NUEVO){
        this.USUARIO_ADMINISTRADOR_NOMBRE=USUARIO_ADMINISTRADOR_NOMBRE;
        this.NOMBRE_NUEVO = NOMBRE_NUEVO;
    }
    public PerfilAdministrador (int PERFIL_ADMINISTRADOR_ID){
        this.PERFIL_ADMINISTRADOR_ID = PERFIL_ADMINISTRADOR_ID;
    }
    //Getters y Setters
    public int getPERFIL_ADMINISTRADOR_ID() {
        return PERFIL_ADMINISTRADOR_ID;
    }

    public void setPERFIL_ADMINISTRADOR_ID(int PERFIL_ADMINISTRADOR_ID) {
        this.PERFIL_ADMINISTRADOR_ID = PERFIL_ADMINISTRADOR_ID;
    }

    public String getCONTRASENA_ADMINISTRADOR_NOMBRE() {
        return CONTRASENA_ADMINISTRADOR_NOMBRE;
    }

    public void setCONTRASENA_ADMINISTRADOR_NOMBRE(String CONTRASENA_ADMINISTRADOR_NOMBRE) {
        this.CONTRASENA_ADMINISTRADOR_NOMBRE = CONTRASENA_ADMINISTRADOR_NOMBRE;
    }

    public String getCEDULA_ADMINISTRADOR_NOMBRE() {
        return CEDULA_ADMINISTRADOR_NOMBRE;
    }

    public void setCEDULA_ADMINISTRADOR_NOMBRE(String CEDULA_ADMINISTRADOR_NOMBRE) {
        this.CEDULA_ADMINISTRADOR_NOMBRE = CEDULA_ADMINISTRADOR_NOMBRE;
    }

    public String getUSUARIO_ADMINISTRADOR_NOMBRE() {
        return USUARIO_ADMINISTRADOR_NOMBRE;
    }

    public void setUSUARIO_ADMINISTRADOR_NOMBRE(String USUARIO_ADMINISTRADOR_NOMBRE) {
        this.USUARIO_ADMINISTRADOR_NOMBRE = USUARIO_ADMINISTRADOR_NOMBRE;
    }

    public String getPERFIL_ADMINISTRADOR_ESTADO() {
        return PERFIL_ADMINISTRADOR_ESTADO;
    }

    public void setPERFIL_ADMINISTRADOR_ESTADO(String PERFIL_ADMINISTRADOR_ESTADO) {
        this.PERFIL_ADMINISTRADOR_ESTADO = PERFIL_ADMINISTRADOR_ESTADO;
    }

    public String getNOMBRE_NUEVO() {
        return NOMBRE_NUEVO;
    }
    public void setNOMBRE_NUEVO(String nOMBRE_NUEVO) {
        NOMBRE_NUEVO = nOMBRE_NUEVO;
    }
}
